### ISSUE TITLE
Cannot compile as dependency

### ISSUE THREAD

**Issue by dannypsnl** [peburrows/diplomat#54]
```
== Compilation error in file lib/diplomat.ex ==
** (Protobuf.Parser.ParserError) [missing_occurrence, missing_occurrence, missing_occurrence, missing_occurrence]
    (exprotobuf 1.2.17) lib/exprotobuf/parser.ex:101: Protobuf.Parser.parse!/3
    (elixir 1.12.0) lib/enum.ex:3865: Enum.flat_map_list/2
    (exprotobuf 1.2.17) lib/exprotobuf/parser.ex:8: Protobuf.Parser.parse_files!/2
    (exprotobuf 1.2.17) lib/exprotobuf.ex:194: Protobuf.parse/2
    (exprotobuf 1.2.17) expanding macro: Protobuf.__using__/1
    lib/diplomat.ex:10: Diplomat.Proto (module)
    (elixir 1.12.0) expanding macro: Kernel.use/2
    lib/diplomat.ex:10: Diplomat.Proto (module)
```

**Comment by brunoripa** [comment]
Same for me.

**Comment by kapil4161** [comment]
same could not resolve

**Comment by dannypsnl** [comment]
Not resolved, but just this repo seems to get abandoned, and I pick another library in the end.
